/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PartyOptionsModel struct for PartyOptionsModel
type PartyOptionsModel struct {
	// 
	IncludeTags *bool `json:"include_tags,omitempty"`
	// 
	IncludeTagIds *bool `json:"include_tag_ids,omitempty"`
	// 
	IncludeTagNames *bool `json:"include_tag_names,omitempty"`
	// 
	IncludeLinks *bool `json:"include_links,omitempty"`
	// 
	IncludeMetaData *bool `json:"include_meta_data,omitempty"`
	// 
	IncludeNotes *bool `json:"include_notes,omitempty"`
	// 
	IncludeRecordInfo *bool `json:"include_record_info,omitempty"`
	// 
	IncludePartyTypeName *bool `json:"include_party_type_name,omitempty"`
}

// NewPartyOptionsModel instantiates a new PartyOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartyOptionsModel() *PartyOptionsModel {
	this := PartyOptionsModel{}
	return &this
}

// NewPartyOptionsModelWithDefaults instantiates a new PartyOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyOptionsModelWithDefaults() *PartyOptionsModel {
	this := PartyOptionsModel{}
	return &this
}

// GetIncludeTags returns the IncludeTags field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeTags() bool {
	if o == nil || o.IncludeTags == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTags
}

// GetIncludeTagsOk returns a tuple with the IncludeTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeTagsOk() (*bool, bool) {
	if o == nil || o.IncludeTags == nil {
		return nil, false
	}
	return o.IncludeTags, true
}

// HasIncludeTags returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeTags() bool {
	if o != nil && o.IncludeTags != nil {
		return true
	}

	return false
}

// SetIncludeTags gets a reference to the given bool and assigns it to the IncludeTags field.
func (o *PartyOptionsModel) SetIncludeTags(v bool) {
	o.IncludeTags = &v
}

// GetIncludeTagIds returns the IncludeTagIds field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeTagIds() bool {
	if o == nil || o.IncludeTagIds == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTagIds
}

// GetIncludeTagIdsOk returns a tuple with the IncludeTagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeTagIdsOk() (*bool, bool) {
	if o == nil || o.IncludeTagIds == nil {
		return nil, false
	}
	return o.IncludeTagIds, true
}

// HasIncludeTagIds returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeTagIds() bool {
	if o != nil && o.IncludeTagIds != nil {
		return true
	}

	return false
}

// SetIncludeTagIds gets a reference to the given bool and assigns it to the IncludeTagIds field.
func (o *PartyOptionsModel) SetIncludeTagIds(v bool) {
	o.IncludeTagIds = &v
}

// GetIncludeTagNames returns the IncludeTagNames field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeTagNames() bool {
	if o == nil || o.IncludeTagNames == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTagNames
}

// GetIncludeTagNamesOk returns a tuple with the IncludeTagNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeTagNamesOk() (*bool, bool) {
	if o == nil || o.IncludeTagNames == nil {
		return nil, false
	}
	return o.IncludeTagNames, true
}

// HasIncludeTagNames returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeTagNames() bool {
	if o != nil && o.IncludeTagNames != nil {
		return true
	}

	return false
}

// SetIncludeTagNames gets a reference to the given bool and assigns it to the IncludeTagNames field.
func (o *PartyOptionsModel) SetIncludeTagNames(v bool) {
	o.IncludeTagNames = &v
}

// GetIncludeLinks returns the IncludeLinks field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeLinks() bool {
	if o == nil || o.IncludeLinks == nil {
		var ret bool
		return ret
	}
	return *o.IncludeLinks
}

// GetIncludeLinksOk returns a tuple with the IncludeLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeLinksOk() (*bool, bool) {
	if o == nil || o.IncludeLinks == nil {
		return nil, false
	}
	return o.IncludeLinks, true
}

// HasIncludeLinks returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeLinks() bool {
	if o != nil && o.IncludeLinks != nil {
		return true
	}

	return false
}

// SetIncludeLinks gets a reference to the given bool and assigns it to the IncludeLinks field.
func (o *PartyOptionsModel) SetIncludeLinks(v bool) {
	o.IncludeLinks = &v
}

// GetIncludeMetaData returns the IncludeMetaData field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeMetaData() bool {
	if o == nil || o.IncludeMetaData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeMetaData
}

// GetIncludeMetaDataOk returns a tuple with the IncludeMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeMetaDataOk() (*bool, bool) {
	if o == nil || o.IncludeMetaData == nil {
		return nil, false
	}
	return o.IncludeMetaData, true
}

// HasIncludeMetaData returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeMetaData() bool {
	if o != nil && o.IncludeMetaData != nil {
		return true
	}

	return false
}

// SetIncludeMetaData gets a reference to the given bool and assigns it to the IncludeMetaData field.
func (o *PartyOptionsModel) SetIncludeMetaData(v bool) {
	o.IncludeMetaData = &v
}

// GetIncludeNotes returns the IncludeNotes field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeNotes() bool {
	if o == nil || o.IncludeNotes == nil {
		var ret bool
		return ret
	}
	return *o.IncludeNotes
}

// GetIncludeNotesOk returns a tuple with the IncludeNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeNotesOk() (*bool, bool) {
	if o == nil || o.IncludeNotes == nil {
		return nil, false
	}
	return o.IncludeNotes, true
}

// HasIncludeNotes returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeNotes() bool {
	if o != nil && o.IncludeNotes != nil {
		return true
	}

	return false
}

// SetIncludeNotes gets a reference to the given bool and assigns it to the IncludeNotes field.
func (o *PartyOptionsModel) SetIncludeNotes(v bool) {
	o.IncludeNotes = &v
}

// GetIncludeRecordInfo returns the IncludeRecordInfo field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludeRecordInfo() bool {
	if o == nil || o.IncludeRecordInfo == nil {
		var ret bool
		return ret
	}
	return *o.IncludeRecordInfo
}

// GetIncludeRecordInfoOk returns a tuple with the IncludeRecordInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludeRecordInfoOk() (*bool, bool) {
	if o == nil || o.IncludeRecordInfo == nil {
		return nil, false
	}
	return o.IncludeRecordInfo, true
}

// HasIncludeRecordInfo returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludeRecordInfo() bool {
	if o != nil && o.IncludeRecordInfo != nil {
		return true
	}

	return false
}

// SetIncludeRecordInfo gets a reference to the given bool and assigns it to the IncludeRecordInfo field.
func (o *PartyOptionsModel) SetIncludeRecordInfo(v bool) {
	o.IncludeRecordInfo = &v
}

// GetIncludePartyTypeName returns the IncludePartyTypeName field value if set, zero value otherwise.
func (o *PartyOptionsModel) GetIncludePartyTypeName() bool {
	if o == nil || o.IncludePartyTypeName == nil {
		var ret bool
		return ret
	}
	return *o.IncludePartyTypeName
}

// GetIncludePartyTypeNameOk returns a tuple with the IncludePartyTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyOptionsModel) GetIncludePartyTypeNameOk() (*bool, bool) {
	if o == nil || o.IncludePartyTypeName == nil {
		return nil, false
	}
	return o.IncludePartyTypeName, true
}

// HasIncludePartyTypeName returns a boolean if a field has been set.
func (o *PartyOptionsModel) HasIncludePartyTypeName() bool {
	if o != nil && o.IncludePartyTypeName != nil {
		return true
	}

	return false
}

// SetIncludePartyTypeName gets a reference to the given bool and assigns it to the IncludePartyTypeName field.
func (o *PartyOptionsModel) SetIncludePartyTypeName(v bool) {
	o.IncludePartyTypeName = &v
}

func (o PartyOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludeTags != nil {
		toSerialize["include_tags"] = o.IncludeTags
	}
	if o.IncludeTagIds != nil {
		toSerialize["include_tag_ids"] = o.IncludeTagIds
	}
	if o.IncludeTagNames != nil {
		toSerialize["include_tag_names"] = o.IncludeTagNames
	}
	if o.IncludeLinks != nil {
		toSerialize["include_links"] = o.IncludeLinks
	}
	if o.IncludeMetaData != nil {
		toSerialize["include_meta_data"] = o.IncludeMetaData
	}
	if o.IncludeNotes != nil {
		toSerialize["include_notes"] = o.IncludeNotes
	}
	if o.IncludeRecordInfo != nil {
		toSerialize["include_record_info"] = o.IncludeRecordInfo
	}
	if o.IncludePartyTypeName != nil {
		toSerialize["include_party_type_name"] = o.IncludePartyTypeName
	}
	return json.Marshal(toSerialize)
}

type NullablePartyOptionsModel struct {
	value *PartyOptionsModel
	isSet bool
}

func (v NullablePartyOptionsModel) Get() *PartyOptionsModel {
	return v.value
}

func (v *NullablePartyOptionsModel) Set(val *PartyOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePartyOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePartyOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartyOptionsModel(val *PartyOptionsModel) *NullablePartyOptionsModel {
	return &NullablePartyOptionsModel{value: val, isSet: true}
}

func (v NullablePartyOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartyOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


