/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceWindowsSchemeFiltersModel struct for ServiceWindowsSchemeFiltersModel
type ServiceWindowsSchemeFiltersModel struct {
	// Service window scheme id's to filter by
	Id *[]int32 `json:"id,omitempty"`
	// Name of the service windows scheme(s) to filter by
	Name *[]string `json:"name,omitempty"`
	// tags to filter by
	TagNames *[]string `json:"tag_names,omitempty"`
	// tag ID's to filter by
	TagIds *[]int32 `json:"tag_ids,omitempty"`
	// zones to filter by
	ZoneNames *[]string `json:"zone_names,omitempty"`
	// zone ID's to filter by
	ZoneIds *[]int32 `json:"zone_ids,omitempty"`
	// brands to filter by
	BrandNames *[]string `json:"brand_names,omitempty"`
	// brand ID's to filter by
	BrandIds *[]int32 `json:"brand_ids,omitempty"`
}

// NewServiceWindowsSchemeFiltersModel instantiates a new ServiceWindowsSchemeFiltersModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceWindowsSchemeFiltersModel() *ServiceWindowsSchemeFiltersModel {
	this := ServiceWindowsSchemeFiltersModel{}
	return &this
}

// NewServiceWindowsSchemeFiltersModelWithDefaults instantiates a new ServiceWindowsSchemeFiltersModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWindowsSchemeFiltersModelWithDefaults() *ServiceWindowsSchemeFiltersModel {
	this := ServiceWindowsSchemeFiltersModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetId() []int32 {
	if o == nil || o.Id == nil {
		var ret []int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetIdOk() (*[]int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given []int32 and assigns it to the Id field.
func (o *ServiceWindowsSchemeFiltersModel) SetId(v []int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetName() []string {
	if o == nil || o.Name == nil {
		var ret []string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetNameOk() (*[]string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given []string and assigns it to the Name field.
func (o *ServiceWindowsSchemeFiltersModel) SetName(v []string) {
	o.Name = &v
}

// GetTagNames returns the TagNames field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetTagNames() []string {
	if o == nil || o.TagNames == nil {
		var ret []string
		return ret
	}
	return *o.TagNames
}

// GetTagNamesOk returns a tuple with the TagNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetTagNamesOk() (*[]string, bool) {
	if o == nil || o.TagNames == nil {
		return nil, false
	}
	return o.TagNames, true
}

// HasTagNames returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasTagNames() bool {
	if o != nil && o.TagNames != nil {
		return true
	}

	return false
}

// SetTagNames gets a reference to the given []string and assigns it to the TagNames field.
func (o *ServiceWindowsSchemeFiltersModel) SetTagNames(v []string) {
	o.TagNames = &v
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetTagIds() []int32 {
	if o == nil || o.TagIds == nil {
		var ret []int32
		return ret
	}
	return *o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetTagIdsOk() (*[]int32, bool) {
	if o == nil || o.TagIds == nil {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasTagIds() bool {
	if o != nil && o.TagIds != nil {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []int32 and assigns it to the TagIds field.
func (o *ServiceWindowsSchemeFiltersModel) SetTagIds(v []int32) {
	o.TagIds = &v
}

// GetZoneNames returns the ZoneNames field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetZoneNames() []string {
	if o == nil || o.ZoneNames == nil {
		var ret []string
		return ret
	}
	return *o.ZoneNames
}

// GetZoneNamesOk returns a tuple with the ZoneNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetZoneNamesOk() (*[]string, bool) {
	if o == nil || o.ZoneNames == nil {
		return nil, false
	}
	return o.ZoneNames, true
}

// HasZoneNames returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasZoneNames() bool {
	if o != nil && o.ZoneNames != nil {
		return true
	}

	return false
}

// SetZoneNames gets a reference to the given []string and assigns it to the ZoneNames field.
func (o *ServiceWindowsSchemeFiltersModel) SetZoneNames(v []string) {
	o.ZoneNames = &v
}

// GetZoneIds returns the ZoneIds field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetZoneIds() []int32 {
	if o == nil || o.ZoneIds == nil {
		var ret []int32
		return ret
	}
	return *o.ZoneIds
}

// GetZoneIdsOk returns a tuple with the ZoneIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetZoneIdsOk() (*[]int32, bool) {
	if o == nil || o.ZoneIds == nil {
		return nil, false
	}
	return o.ZoneIds, true
}

// HasZoneIds returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasZoneIds() bool {
	if o != nil && o.ZoneIds != nil {
		return true
	}

	return false
}

// SetZoneIds gets a reference to the given []int32 and assigns it to the ZoneIds field.
func (o *ServiceWindowsSchemeFiltersModel) SetZoneIds(v []int32) {
	o.ZoneIds = &v
}

// GetBrandNames returns the BrandNames field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetBrandNames() []string {
	if o == nil || o.BrandNames == nil {
		var ret []string
		return ret
	}
	return *o.BrandNames
}

// GetBrandNamesOk returns a tuple with the BrandNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetBrandNamesOk() (*[]string, bool) {
	if o == nil || o.BrandNames == nil {
		return nil, false
	}
	return o.BrandNames, true
}

// HasBrandNames returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasBrandNames() bool {
	if o != nil && o.BrandNames != nil {
		return true
	}

	return false
}

// SetBrandNames gets a reference to the given []string and assigns it to the BrandNames field.
func (o *ServiceWindowsSchemeFiltersModel) SetBrandNames(v []string) {
	o.BrandNames = &v
}

// GetBrandIds returns the BrandIds field value if set, zero value otherwise.
func (o *ServiceWindowsSchemeFiltersModel) GetBrandIds() []int32 {
	if o == nil || o.BrandIds == nil {
		var ret []int32
		return ret
	}
	return *o.BrandIds
}

// GetBrandIdsOk returns a tuple with the BrandIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowsSchemeFiltersModel) GetBrandIdsOk() (*[]int32, bool) {
	if o == nil || o.BrandIds == nil {
		return nil, false
	}
	return o.BrandIds, true
}

// HasBrandIds returns a boolean if a field has been set.
func (o *ServiceWindowsSchemeFiltersModel) HasBrandIds() bool {
	if o != nil && o.BrandIds != nil {
		return true
	}

	return false
}

// SetBrandIds gets a reference to the given []int32 and assigns it to the BrandIds field.
func (o *ServiceWindowsSchemeFiltersModel) SetBrandIds(v []int32) {
	o.BrandIds = &v
}

func (o ServiceWindowsSchemeFiltersModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.TagNames != nil {
		toSerialize["tag_names"] = o.TagNames
	}
	if o.TagIds != nil {
		toSerialize["tag_ids"] = o.TagIds
	}
	if o.ZoneNames != nil {
		toSerialize["zone_names"] = o.ZoneNames
	}
	if o.ZoneIds != nil {
		toSerialize["zone_ids"] = o.ZoneIds
	}
	if o.BrandNames != nil {
		toSerialize["brand_names"] = o.BrandNames
	}
	if o.BrandIds != nil {
		toSerialize["brand_ids"] = o.BrandIds
	}
	return json.Marshal(toSerialize)
}

type NullableServiceWindowsSchemeFiltersModel struct {
	value *ServiceWindowsSchemeFiltersModel
	isSet bool
}

func (v NullableServiceWindowsSchemeFiltersModel) Get() *ServiceWindowsSchemeFiltersModel {
	return v.value
}

func (v *NullableServiceWindowsSchemeFiltersModel) Set(val *ServiceWindowsSchemeFiltersModel) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceWindowsSchemeFiltersModel) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceWindowsSchemeFiltersModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceWindowsSchemeFiltersModel(val *ServiceWindowsSchemeFiltersModel) *NullableServiceWindowsSchemeFiltersModel {
	return &NullableServiceWindowsSchemeFiltersModel{value: val, isSet: true}
}

func (v NullableServiceWindowsSchemeFiltersModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceWindowsSchemeFiltersModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


