/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CredentialsModel struct for CredentialsModel
type CredentialsModel struct {
	// Email
	Email *string `json:"email,omitempty"`
	// Password
	Password *string `json:"password,omitempty"`
	// Set to true for requesting a jwt token
	ReturnJwt *bool `json:"return_jwt,omitempty"`
}

// NewCredentialsModel instantiates a new CredentialsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsModel() *CredentialsModel {
	this := CredentialsModel{}
	return &this
}

// NewCredentialsModelWithDefaults instantiates a new CredentialsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsModelWithDefaults() *CredentialsModel {
	this := CredentialsModel{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CredentialsModel) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsModel) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CredentialsModel) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CredentialsModel) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CredentialsModel) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsModel) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CredentialsModel) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CredentialsModel) SetPassword(v string) {
	o.Password = &v
}

// GetReturnJwt returns the ReturnJwt field value if set, zero value otherwise.
func (o *CredentialsModel) GetReturnJwt() bool {
	if o == nil || o.ReturnJwt == nil {
		var ret bool
		return ret
	}
	return *o.ReturnJwt
}

// GetReturnJwtOk returns a tuple with the ReturnJwt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsModel) GetReturnJwtOk() (*bool, bool) {
	if o == nil || o.ReturnJwt == nil {
		return nil, false
	}
	return o.ReturnJwt, true
}

// HasReturnJwt returns a boolean if a field has been set.
func (o *CredentialsModel) HasReturnJwt() bool {
	if o != nil && o.ReturnJwt != nil {
		return true
	}

	return false
}

// SetReturnJwt gets a reference to the given bool and assigns it to the ReturnJwt field.
func (o *CredentialsModel) SetReturnJwt(v bool) {
	o.ReturnJwt = &v
}

func (o CredentialsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.ReturnJwt != nil {
		toSerialize["return_jwt"] = o.ReturnJwt
	}
	return json.Marshal(toSerialize)
}

type NullableCredentialsModel struct {
	value *CredentialsModel
	isSet bool
}

func (v NullableCredentialsModel) Get() *CredentialsModel {
	return v.value
}

func (v *NullableCredentialsModel) Set(val *CredentialsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsModel(val *CredentialsModel) *NullableCredentialsModel {
	return &NullableCredentialsModel{value: val, isSet: true}
}

func (v NullableCredentialsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


