/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QuestionnaireGetPreviousQuestionArguments struct for QuestionnaireGetPreviousQuestionArguments
type QuestionnaireGetPreviousQuestionArguments struct {
	// Questionnaire ID
	QuestionnaireId *int32 `json:"questionnaire_id,omitempty"`
	// Question ID
	QuestionnaireQuestionId *int32 `json:"questionnaire_question_id,omitempty"`
}

// NewQuestionnaireGetPreviousQuestionArguments instantiates a new QuestionnaireGetPreviousQuestionArguments object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestionnaireGetPreviousQuestionArguments() *QuestionnaireGetPreviousQuestionArguments {
	this := QuestionnaireGetPreviousQuestionArguments{}
	return &this
}

// NewQuestionnaireGetPreviousQuestionArgumentsWithDefaults instantiates a new QuestionnaireGetPreviousQuestionArguments object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestionnaireGetPreviousQuestionArgumentsWithDefaults() *QuestionnaireGetPreviousQuestionArguments {
	this := QuestionnaireGetPreviousQuestionArguments{}
	return &this
}

// GetQuestionnaireId returns the QuestionnaireId field value if set, zero value otherwise.
func (o *QuestionnaireGetPreviousQuestionArguments) GetQuestionnaireId() int32 {
	if o == nil || o.QuestionnaireId == nil {
		var ret int32
		return ret
	}
	return *o.QuestionnaireId
}

// GetQuestionnaireIdOk returns a tuple with the QuestionnaireId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireGetPreviousQuestionArguments) GetQuestionnaireIdOk() (*int32, bool) {
	if o == nil || o.QuestionnaireId == nil {
		return nil, false
	}
	return o.QuestionnaireId, true
}

// HasQuestionnaireId returns a boolean if a field has been set.
func (o *QuestionnaireGetPreviousQuestionArguments) HasQuestionnaireId() bool {
	if o != nil && o.QuestionnaireId != nil {
		return true
	}

	return false
}

// SetQuestionnaireId gets a reference to the given int32 and assigns it to the QuestionnaireId field.
func (o *QuestionnaireGetPreviousQuestionArguments) SetQuestionnaireId(v int32) {
	o.QuestionnaireId = &v
}

// GetQuestionnaireQuestionId returns the QuestionnaireQuestionId field value if set, zero value otherwise.
func (o *QuestionnaireGetPreviousQuestionArguments) GetQuestionnaireQuestionId() int32 {
	if o == nil || o.QuestionnaireQuestionId == nil {
		var ret int32
		return ret
	}
	return *o.QuestionnaireQuestionId
}

// GetQuestionnaireQuestionIdOk returns a tuple with the QuestionnaireQuestionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireGetPreviousQuestionArguments) GetQuestionnaireQuestionIdOk() (*int32, bool) {
	if o == nil || o.QuestionnaireQuestionId == nil {
		return nil, false
	}
	return o.QuestionnaireQuestionId, true
}

// HasQuestionnaireQuestionId returns a boolean if a field has been set.
func (o *QuestionnaireGetPreviousQuestionArguments) HasQuestionnaireQuestionId() bool {
	if o != nil && o.QuestionnaireQuestionId != nil {
		return true
	}

	return false
}

// SetQuestionnaireQuestionId gets a reference to the given int32 and assigns it to the QuestionnaireQuestionId field.
func (o *QuestionnaireGetPreviousQuestionArguments) SetQuestionnaireQuestionId(v int32) {
	o.QuestionnaireQuestionId = &v
}

func (o QuestionnaireGetPreviousQuestionArguments) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.QuestionnaireId != nil {
		toSerialize["questionnaire_id"] = o.QuestionnaireId
	}
	if o.QuestionnaireQuestionId != nil {
		toSerialize["questionnaire_question_id"] = o.QuestionnaireQuestionId
	}
	return json.Marshal(toSerialize)
}

type NullableQuestionnaireGetPreviousQuestionArguments struct {
	value *QuestionnaireGetPreviousQuestionArguments
	isSet bool
}

func (v NullableQuestionnaireGetPreviousQuestionArguments) Get() *QuestionnaireGetPreviousQuestionArguments {
	return v.value
}

func (v *NullableQuestionnaireGetPreviousQuestionArguments) Set(val *QuestionnaireGetPreviousQuestionArguments) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestionnaireGetPreviousQuestionArguments) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestionnaireGetPreviousQuestionArguments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestionnaireGetPreviousQuestionArguments(val *QuestionnaireGetPreviousQuestionArguments) *NullableQuestionnaireGetPreviousQuestionArguments {
	return &NullableQuestionnaireGetPreviousQuestionArguments{value: val, isSet: true}
}

func (v NullableQuestionnaireGetPreviousQuestionArguments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestionnaireGetPreviousQuestionArguments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


