/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// SettingsFiltersModel struct for SettingsFiltersModel
type SettingsFiltersModel struct {
	// 
	Id *[]int32 `json:"id,omitempty"`
	// SettingsGroup id of this setting. Possible values: 1: general, 2: address, 3: package, 4: activity, 5: equipment, 6: note, 7: optimisation, 8: filters
	SettingsGroupId *[]int32 `json:"settings_group_id,omitempty"`
	// SettingsGroup name of this setting
	SettingsGroupName *[]string `json:"settings_group_name,omitempty"`
	// Unique string key for setting identification
	Key *[]string `json:"key,omitempty"`
	// free search through text and numeric type columns
	SearchText *string `json:"search_text,omitempty"`
	// Show updated since
	UpdatedAtSince *time.Time `json:"updated_at_since,omitempty"`
	// Show updated till
	UpdatedAtTill *time.Time `json:"updated_at_till,omitempty"`
}

// NewSettingsFiltersModel instantiates a new SettingsFiltersModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsFiltersModel() *SettingsFiltersModel {
	this := SettingsFiltersModel{}
	return &this
}

// NewSettingsFiltersModelWithDefaults instantiates a new SettingsFiltersModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsFiltersModelWithDefaults() *SettingsFiltersModel {
	this := SettingsFiltersModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetId() []int32 {
	if o == nil || o.Id == nil {
		var ret []int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetIdOk() (*[]int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given []int32 and assigns it to the Id field.
func (o *SettingsFiltersModel) SetId(v []int32) {
	o.Id = &v
}

// GetSettingsGroupId returns the SettingsGroupId field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetSettingsGroupId() []int32 {
	if o == nil || o.SettingsGroupId == nil {
		var ret []int32
		return ret
	}
	return *o.SettingsGroupId
}

// GetSettingsGroupIdOk returns a tuple with the SettingsGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetSettingsGroupIdOk() (*[]int32, bool) {
	if o == nil || o.SettingsGroupId == nil {
		return nil, false
	}
	return o.SettingsGroupId, true
}

// HasSettingsGroupId returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasSettingsGroupId() bool {
	if o != nil && o.SettingsGroupId != nil {
		return true
	}

	return false
}

// SetSettingsGroupId gets a reference to the given []int32 and assigns it to the SettingsGroupId field.
func (o *SettingsFiltersModel) SetSettingsGroupId(v []int32) {
	o.SettingsGroupId = &v
}

// GetSettingsGroupName returns the SettingsGroupName field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetSettingsGroupName() []string {
	if o == nil || o.SettingsGroupName == nil {
		var ret []string
		return ret
	}
	return *o.SettingsGroupName
}

// GetSettingsGroupNameOk returns a tuple with the SettingsGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetSettingsGroupNameOk() (*[]string, bool) {
	if o == nil || o.SettingsGroupName == nil {
		return nil, false
	}
	return o.SettingsGroupName, true
}

// HasSettingsGroupName returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasSettingsGroupName() bool {
	if o != nil && o.SettingsGroupName != nil {
		return true
	}

	return false
}

// SetSettingsGroupName gets a reference to the given []string and assigns it to the SettingsGroupName field.
func (o *SettingsFiltersModel) SetSettingsGroupName(v []string) {
	o.SettingsGroupName = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetKey() []string {
	if o == nil || o.Key == nil {
		var ret []string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetKeyOk() (*[]string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given []string and assigns it to the Key field.
func (o *SettingsFiltersModel) SetKey(v []string) {
	o.Key = &v
}

// GetSearchText returns the SearchText field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetSearchText() string {
	if o == nil || o.SearchText == nil {
		var ret string
		return ret
	}
	return *o.SearchText
}

// GetSearchTextOk returns a tuple with the SearchText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetSearchTextOk() (*string, bool) {
	if o == nil || o.SearchText == nil {
		return nil, false
	}
	return o.SearchText, true
}

// HasSearchText returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasSearchText() bool {
	if o != nil && o.SearchText != nil {
		return true
	}

	return false
}

// SetSearchText gets a reference to the given string and assigns it to the SearchText field.
func (o *SettingsFiltersModel) SetSearchText(v string) {
	o.SearchText = &v
}

// GetUpdatedAtSince returns the UpdatedAtSince field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetUpdatedAtSince() time.Time {
	if o == nil || o.UpdatedAtSince == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtSince
}

// GetUpdatedAtSinceOk returns a tuple with the UpdatedAtSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetUpdatedAtSinceOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAtSince == nil {
		return nil, false
	}
	return o.UpdatedAtSince, true
}

// HasUpdatedAtSince returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasUpdatedAtSince() bool {
	if o != nil && o.UpdatedAtSince != nil {
		return true
	}

	return false
}

// SetUpdatedAtSince gets a reference to the given time.Time and assigns it to the UpdatedAtSince field.
func (o *SettingsFiltersModel) SetUpdatedAtSince(v time.Time) {
	o.UpdatedAtSince = &v
}

// GetUpdatedAtTill returns the UpdatedAtTill field value if set, zero value otherwise.
func (o *SettingsFiltersModel) GetUpdatedAtTill() time.Time {
	if o == nil || o.UpdatedAtTill == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtTill
}

// GetUpdatedAtTillOk returns a tuple with the UpdatedAtTill field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsFiltersModel) GetUpdatedAtTillOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAtTill == nil {
		return nil, false
	}
	return o.UpdatedAtTill, true
}

// HasUpdatedAtTill returns a boolean if a field has been set.
func (o *SettingsFiltersModel) HasUpdatedAtTill() bool {
	if o != nil && o.UpdatedAtTill != nil {
		return true
	}

	return false
}

// SetUpdatedAtTill gets a reference to the given time.Time and assigns it to the UpdatedAtTill field.
func (o *SettingsFiltersModel) SetUpdatedAtTill(v time.Time) {
	o.UpdatedAtTill = &v
}

func (o SettingsFiltersModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.SettingsGroupId != nil {
		toSerialize["settings_group_id"] = o.SettingsGroupId
	}
	if o.SettingsGroupName != nil {
		toSerialize["settings_group_name"] = o.SettingsGroupName
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.SearchText != nil {
		toSerialize["search_text"] = o.SearchText
	}
	if o.UpdatedAtSince != nil {
		toSerialize["updated_at_since"] = o.UpdatedAtSince
	}
	if o.UpdatedAtTill != nil {
		toSerialize["updated_at_till"] = o.UpdatedAtTill
	}
	return json.Marshal(toSerialize)
}

type NullableSettingsFiltersModel struct {
	value *SettingsFiltersModel
	isSet bool
}

func (v NullableSettingsFiltersModel) Get() *SettingsFiltersModel {
	return v.value
}

func (v *NullableSettingsFiltersModel) Set(val *SettingsFiltersModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsFiltersModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsFiltersModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsFiltersModel(val *SettingsFiltersModel) *NullableSettingsFiltersModel {
	return &NullableSettingsFiltersModel{value: val, isSet: true}
}

func (v NullableSettingsFiltersModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsFiltersModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


