/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VehicleOptionsModel struct for VehicleOptionsModel
type VehicleOptionsModel struct {
	// 
	IncludeTags *bool `json:"include_tags,omitempty"`
	// 
	IncludeLinks *bool `json:"include_links,omitempty"`
	// 
	IncludeMetaData *bool `json:"include_meta_data,omitempty"`
	// 
	IncludeUpdatedByName *bool `json:"include_updated_by_name,omitempty"`
	// Deprecated! use include_meta_data
	IncludeVehicleMetaData *bool `json:"include_vehicle_meta_data,omitempty"`
	// Deprecated! use include_links
	IncludeVehicleLinks *bool `json:"include_vehicle_links,omitempty"`
	// Deprecated! use include_tags
	IncludeVehicleTags *bool `json:"include_vehicle_tags,omitempty"`
	// Deprecated! use include_tags
	IncludeTagTypeName *bool `json:"include_tag_type_name,omitempty"`
}

// NewVehicleOptionsModel instantiates a new VehicleOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleOptionsModel() *VehicleOptionsModel {
	this := VehicleOptionsModel{}
	return &this
}

// NewVehicleOptionsModelWithDefaults instantiates a new VehicleOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleOptionsModelWithDefaults() *VehicleOptionsModel {
	this := VehicleOptionsModel{}
	return &this
}

// GetIncludeTags returns the IncludeTags field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeTags() bool {
	if o == nil || o.IncludeTags == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTags
}

// GetIncludeTagsOk returns a tuple with the IncludeTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeTagsOk() (*bool, bool) {
	if o == nil || o.IncludeTags == nil {
		return nil, false
	}
	return o.IncludeTags, true
}

// HasIncludeTags returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeTags() bool {
	if o != nil && o.IncludeTags != nil {
		return true
	}

	return false
}

// SetIncludeTags gets a reference to the given bool and assigns it to the IncludeTags field.
func (o *VehicleOptionsModel) SetIncludeTags(v bool) {
	o.IncludeTags = &v
}

// GetIncludeLinks returns the IncludeLinks field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeLinks() bool {
	if o == nil || o.IncludeLinks == nil {
		var ret bool
		return ret
	}
	return *o.IncludeLinks
}

// GetIncludeLinksOk returns a tuple with the IncludeLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeLinksOk() (*bool, bool) {
	if o == nil || o.IncludeLinks == nil {
		return nil, false
	}
	return o.IncludeLinks, true
}

// HasIncludeLinks returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeLinks() bool {
	if o != nil && o.IncludeLinks != nil {
		return true
	}

	return false
}

// SetIncludeLinks gets a reference to the given bool and assigns it to the IncludeLinks field.
func (o *VehicleOptionsModel) SetIncludeLinks(v bool) {
	o.IncludeLinks = &v
}

// GetIncludeMetaData returns the IncludeMetaData field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeMetaData() bool {
	if o == nil || o.IncludeMetaData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeMetaData
}

// GetIncludeMetaDataOk returns a tuple with the IncludeMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeMetaDataOk() (*bool, bool) {
	if o == nil || o.IncludeMetaData == nil {
		return nil, false
	}
	return o.IncludeMetaData, true
}

// HasIncludeMetaData returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeMetaData() bool {
	if o != nil && o.IncludeMetaData != nil {
		return true
	}

	return false
}

// SetIncludeMetaData gets a reference to the given bool and assigns it to the IncludeMetaData field.
func (o *VehicleOptionsModel) SetIncludeMetaData(v bool) {
	o.IncludeMetaData = &v
}

// GetIncludeUpdatedByName returns the IncludeUpdatedByName field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeUpdatedByName() bool {
	if o == nil || o.IncludeUpdatedByName == nil {
		var ret bool
		return ret
	}
	return *o.IncludeUpdatedByName
}

// GetIncludeUpdatedByNameOk returns a tuple with the IncludeUpdatedByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeUpdatedByNameOk() (*bool, bool) {
	if o == nil || o.IncludeUpdatedByName == nil {
		return nil, false
	}
	return o.IncludeUpdatedByName, true
}

// HasIncludeUpdatedByName returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeUpdatedByName() bool {
	if o != nil && o.IncludeUpdatedByName != nil {
		return true
	}

	return false
}

// SetIncludeUpdatedByName gets a reference to the given bool and assigns it to the IncludeUpdatedByName field.
func (o *VehicleOptionsModel) SetIncludeUpdatedByName(v bool) {
	o.IncludeUpdatedByName = &v
}

// GetIncludeVehicleMetaData returns the IncludeVehicleMetaData field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeVehicleMetaData() bool {
	if o == nil || o.IncludeVehicleMetaData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeVehicleMetaData
}

// GetIncludeVehicleMetaDataOk returns a tuple with the IncludeVehicleMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeVehicleMetaDataOk() (*bool, bool) {
	if o == nil || o.IncludeVehicleMetaData == nil {
		return nil, false
	}
	return o.IncludeVehicleMetaData, true
}

// HasIncludeVehicleMetaData returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeVehicleMetaData() bool {
	if o != nil && o.IncludeVehicleMetaData != nil {
		return true
	}

	return false
}

// SetIncludeVehicleMetaData gets a reference to the given bool and assigns it to the IncludeVehicleMetaData field.
func (o *VehicleOptionsModel) SetIncludeVehicleMetaData(v bool) {
	o.IncludeVehicleMetaData = &v
}

// GetIncludeVehicleLinks returns the IncludeVehicleLinks field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeVehicleLinks() bool {
	if o == nil || o.IncludeVehicleLinks == nil {
		var ret bool
		return ret
	}
	return *o.IncludeVehicleLinks
}

// GetIncludeVehicleLinksOk returns a tuple with the IncludeVehicleLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeVehicleLinksOk() (*bool, bool) {
	if o == nil || o.IncludeVehicleLinks == nil {
		return nil, false
	}
	return o.IncludeVehicleLinks, true
}

// HasIncludeVehicleLinks returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeVehicleLinks() bool {
	if o != nil && o.IncludeVehicleLinks != nil {
		return true
	}

	return false
}

// SetIncludeVehicleLinks gets a reference to the given bool and assigns it to the IncludeVehicleLinks field.
func (o *VehicleOptionsModel) SetIncludeVehicleLinks(v bool) {
	o.IncludeVehicleLinks = &v
}

// GetIncludeVehicleTags returns the IncludeVehicleTags field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeVehicleTags() bool {
	if o == nil || o.IncludeVehicleTags == nil {
		var ret bool
		return ret
	}
	return *o.IncludeVehicleTags
}

// GetIncludeVehicleTagsOk returns a tuple with the IncludeVehicleTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeVehicleTagsOk() (*bool, bool) {
	if o == nil || o.IncludeVehicleTags == nil {
		return nil, false
	}
	return o.IncludeVehicleTags, true
}

// HasIncludeVehicleTags returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeVehicleTags() bool {
	if o != nil && o.IncludeVehicleTags != nil {
		return true
	}

	return false
}

// SetIncludeVehicleTags gets a reference to the given bool and assigns it to the IncludeVehicleTags field.
func (o *VehicleOptionsModel) SetIncludeVehicleTags(v bool) {
	o.IncludeVehicleTags = &v
}

// GetIncludeTagTypeName returns the IncludeTagTypeName field value if set, zero value otherwise.
func (o *VehicleOptionsModel) GetIncludeTagTypeName() bool {
	if o == nil || o.IncludeTagTypeName == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTagTypeName
}

// GetIncludeTagTypeNameOk returns a tuple with the IncludeTagTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleOptionsModel) GetIncludeTagTypeNameOk() (*bool, bool) {
	if o == nil || o.IncludeTagTypeName == nil {
		return nil, false
	}
	return o.IncludeTagTypeName, true
}

// HasIncludeTagTypeName returns a boolean if a field has been set.
func (o *VehicleOptionsModel) HasIncludeTagTypeName() bool {
	if o != nil && o.IncludeTagTypeName != nil {
		return true
	}

	return false
}

// SetIncludeTagTypeName gets a reference to the given bool and assigns it to the IncludeTagTypeName field.
func (o *VehicleOptionsModel) SetIncludeTagTypeName(v bool) {
	o.IncludeTagTypeName = &v
}

func (o VehicleOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludeTags != nil {
		toSerialize["include_tags"] = o.IncludeTags
	}
	if o.IncludeLinks != nil {
		toSerialize["include_links"] = o.IncludeLinks
	}
	if o.IncludeMetaData != nil {
		toSerialize["include_meta_data"] = o.IncludeMetaData
	}
	if o.IncludeUpdatedByName != nil {
		toSerialize["include_updated_by_name"] = o.IncludeUpdatedByName
	}
	if o.IncludeVehicleMetaData != nil {
		toSerialize["include_vehicle_meta_data"] = o.IncludeVehicleMetaData
	}
	if o.IncludeVehicleLinks != nil {
		toSerialize["include_vehicle_links"] = o.IncludeVehicleLinks
	}
	if o.IncludeVehicleTags != nil {
		toSerialize["include_vehicle_tags"] = o.IncludeVehicleTags
	}
	if o.IncludeTagTypeName != nil {
		toSerialize["include_tag_type_name"] = o.IncludeTagTypeName
	}
	return json.Marshal(toSerialize)
}

type NullableVehicleOptionsModel struct {
	value *VehicleOptionsModel
	isSet bool
}

func (v NullableVehicleOptionsModel) Get() *VehicleOptionsModel {
	return v.value
}

func (v *NullableVehicleOptionsModel) Set(val *VehicleOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleOptionsModel(val *VehicleOptionsModel) *NullableVehicleOptionsModel {
	return &NullableVehicleOptionsModel{value: val, isSet: true}
}

func (v NullableVehicleOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


