/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QuestionnaireQuestionTypeModel struct for QuestionnaireQuestionTypeModel
type QuestionnaireQuestionTypeModel struct {
	// Unique Identifier
	Id *int64 `json:"id,omitempty"`
	// if active=0: note has been removed and is no longer visible in any bumbal interface
	Active *bool `json:"active,omitempty"`
	// Name of the question type
	Name *string `json:"name,omitempty"`
}

// NewQuestionnaireQuestionTypeModel instantiates a new QuestionnaireQuestionTypeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestionnaireQuestionTypeModel() *QuestionnaireQuestionTypeModel {
	this := QuestionnaireQuestionTypeModel{}
	return &this
}

// NewQuestionnaireQuestionTypeModelWithDefaults instantiates a new QuestionnaireQuestionTypeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestionnaireQuestionTypeModelWithDefaults() *QuestionnaireQuestionTypeModel {
	this := QuestionnaireQuestionTypeModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *QuestionnaireQuestionTypeModel) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireQuestionTypeModel) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *QuestionnaireQuestionTypeModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *QuestionnaireQuestionTypeModel) SetId(v int64) {
	o.Id = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *QuestionnaireQuestionTypeModel) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireQuestionTypeModel) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *QuestionnaireQuestionTypeModel) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *QuestionnaireQuestionTypeModel) SetActive(v bool) {
	o.Active = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *QuestionnaireQuestionTypeModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireQuestionTypeModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *QuestionnaireQuestionTypeModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *QuestionnaireQuestionTypeModel) SetName(v string) {
	o.Name = &v
}

func (o QuestionnaireQuestionTypeModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableQuestionnaireQuestionTypeModel struct {
	value *QuestionnaireQuestionTypeModel
	isSet bool
}

func (v NullableQuestionnaireQuestionTypeModel) Get() *QuestionnaireQuestionTypeModel {
	return v.value
}

func (v *NullableQuestionnaireQuestionTypeModel) Set(val *QuestionnaireQuestionTypeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestionnaireQuestionTypeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestionnaireQuestionTypeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestionnaireQuestionTypeModel(val *QuestionnaireQuestionTypeModel) *NullableQuestionnaireQuestionTypeModel {
	return &NullableQuestionnaireQuestionTypeModel{value: val, isSet: true}
}

func (v NullableQuestionnaireQuestionTypeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestionnaireQuestionTypeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


