/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CapacityTypeFiltersModel struct for CapacityTypeFiltersModel
type CapacityTypeFiltersModel struct {
	// Bumbal capacity type id's
	Id *[]int32 `json:"id,omitempty"`
	// Bumbal capacity type names
	Name *[]string `json:"name,omitempty"`
}

// NewCapacityTypeFiltersModel instantiates a new CapacityTypeFiltersModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapacityTypeFiltersModel() *CapacityTypeFiltersModel {
	this := CapacityTypeFiltersModel{}
	return &this
}

// NewCapacityTypeFiltersModelWithDefaults instantiates a new CapacityTypeFiltersModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapacityTypeFiltersModelWithDefaults() *CapacityTypeFiltersModel {
	this := CapacityTypeFiltersModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CapacityTypeFiltersModel) GetId() []int32 {
	if o == nil || o.Id == nil {
		var ret []int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityTypeFiltersModel) GetIdOk() (*[]int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CapacityTypeFiltersModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given []int32 and assigns it to the Id field.
func (o *CapacityTypeFiltersModel) SetId(v []int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CapacityTypeFiltersModel) GetName() []string {
	if o == nil || o.Name == nil {
		var ret []string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapacityTypeFiltersModel) GetNameOk() (*[]string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CapacityTypeFiltersModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given []string and assigns it to the Name field.
func (o *CapacityTypeFiltersModel) SetName(v []string) {
	o.Name = &v
}

func (o CapacityTypeFiltersModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCapacityTypeFiltersModel struct {
	value *CapacityTypeFiltersModel
	isSet bool
}

func (v NullableCapacityTypeFiltersModel) Get() *CapacityTypeFiltersModel {
	return v.value
}

func (v *NullableCapacityTypeFiltersModel) Set(val *CapacityTypeFiltersModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCapacityTypeFiltersModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCapacityTypeFiltersModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapacityTypeFiltersModel(val *CapacityTypeFiltersModel) *NullableCapacityTypeFiltersModel {
	return &NullableCapacityTypeFiltersModel{value: val, isSet: true}
}

func (v NullableCapacityTypeFiltersModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapacityTypeFiltersModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


