/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// QuestionnaireTemplateQuestionOptionOptionsModel struct for QuestionnaireTemplateQuestionOptionOptionsModel
type QuestionnaireTemplateQuestionOptionOptionsModel struct {
	// 
	IncludeTexts *bool `json:"include_texts,omitempty"`
}

// NewQuestionnaireTemplateQuestionOptionOptionsModel instantiates a new QuestionnaireTemplateQuestionOptionOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestionnaireTemplateQuestionOptionOptionsModel() *QuestionnaireTemplateQuestionOptionOptionsModel {
	this := QuestionnaireTemplateQuestionOptionOptionsModel{}
	return &this
}

// NewQuestionnaireTemplateQuestionOptionOptionsModelWithDefaults instantiates a new QuestionnaireTemplateQuestionOptionOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestionnaireTemplateQuestionOptionOptionsModelWithDefaults() *QuestionnaireTemplateQuestionOptionOptionsModel {
	this := QuestionnaireTemplateQuestionOptionOptionsModel{}
	return &this
}

// GetIncludeTexts returns the IncludeTexts field value if set, zero value otherwise.
func (o *QuestionnaireTemplateQuestionOptionOptionsModel) GetIncludeTexts() bool {
	if o == nil || o.IncludeTexts == nil {
		var ret bool
		return ret
	}
	return *o.IncludeTexts
}

// GetIncludeTextsOk returns a tuple with the IncludeTexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestionnaireTemplateQuestionOptionOptionsModel) GetIncludeTextsOk() (*bool, bool) {
	if o == nil || o.IncludeTexts == nil {
		return nil, false
	}
	return o.IncludeTexts, true
}

// HasIncludeTexts returns a boolean if a field has been set.
func (o *QuestionnaireTemplateQuestionOptionOptionsModel) HasIncludeTexts() bool {
	if o != nil && o.IncludeTexts != nil {
		return true
	}

	return false
}

// SetIncludeTexts gets a reference to the given bool and assigns it to the IncludeTexts field.
func (o *QuestionnaireTemplateQuestionOptionOptionsModel) SetIncludeTexts(v bool) {
	o.IncludeTexts = &v
}

func (o QuestionnaireTemplateQuestionOptionOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludeTexts != nil {
		toSerialize["include_texts"] = o.IncludeTexts
	}
	return json.Marshal(toSerialize)
}

type NullableQuestionnaireTemplateQuestionOptionOptionsModel struct {
	value *QuestionnaireTemplateQuestionOptionOptionsModel
	isSet bool
}

func (v NullableQuestionnaireTemplateQuestionOptionOptionsModel) Get() *QuestionnaireTemplateQuestionOptionOptionsModel {
	return v.value
}

func (v *NullableQuestionnaireTemplateQuestionOptionOptionsModel) Set(val *QuestionnaireTemplateQuestionOptionOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestionnaireTemplateQuestionOptionOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestionnaireTemplateQuestionOptionOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestionnaireTemplateQuestionOptionOptionsModel(val *QuestionnaireTemplateQuestionOptionOptionsModel) *NullableQuestionnaireTemplateQuestionOptionOptionsModel {
	return &NullableQuestionnaireTemplateQuestionOptionOptionsModel{value: val, isSet: true}
}

func (v NullableQuestionnaireTemplateQuestionOptionOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestionnaireTemplateQuestionOptionOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


