/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CommunicationTemplateOptionsModel struct for CommunicationTemplateOptionsModel
type CommunicationTemplateOptionsModel struct {
	// 
	ExcludeTemplateContent *bool `json:"exclude_template_content,omitempty"`
	// 
	IncludeMappings *bool `json:"include_mappings,omitempty"`
}

// NewCommunicationTemplateOptionsModel instantiates a new CommunicationTemplateOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunicationTemplateOptionsModel() *CommunicationTemplateOptionsModel {
	this := CommunicationTemplateOptionsModel{}
	return &this
}

// NewCommunicationTemplateOptionsModelWithDefaults instantiates a new CommunicationTemplateOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunicationTemplateOptionsModelWithDefaults() *CommunicationTemplateOptionsModel {
	this := CommunicationTemplateOptionsModel{}
	return &this
}

// GetExcludeTemplateContent returns the ExcludeTemplateContent field value if set, zero value otherwise.
func (o *CommunicationTemplateOptionsModel) GetExcludeTemplateContent() bool {
	if o == nil || o.ExcludeTemplateContent == nil {
		var ret bool
		return ret
	}
	return *o.ExcludeTemplateContent
}

// GetExcludeTemplateContentOk returns a tuple with the ExcludeTemplateContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunicationTemplateOptionsModel) GetExcludeTemplateContentOk() (*bool, bool) {
	if o == nil || o.ExcludeTemplateContent == nil {
		return nil, false
	}
	return o.ExcludeTemplateContent, true
}

// HasExcludeTemplateContent returns a boolean if a field has been set.
func (o *CommunicationTemplateOptionsModel) HasExcludeTemplateContent() bool {
	if o != nil && o.ExcludeTemplateContent != nil {
		return true
	}

	return false
}

// SetExcludeTemplateContent gets a reference to the given bool and assigns it to the ExcludeTemplateContent field.
func (o *CommunicationTemplateOptionsModel) SetExcludeTemplateContent(v bool) {
	o.ExcludeTemplateContent = &v
}

// GetIncludeMappings returns the IncludeMappings field value if set, zero value otherwise.
func (o *CommunicationTemplateOptionsModel) GetIncludeMappings() bool {
	if o == nil || o.IncludeMappings == nil {
		var ret bool
		return ret
	}
	return *o.IncludeMappings
}

// GetIncludeMappingsOk returns a tuple with the IncludeMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunicationTemplateOptionsModel) GetIncludeMappingsOk() (*bool, bool) {
	if o == nil || o.IncludeMappings == nil {
		return nil, false
	}
	return o.IncludeMappings, true
}

// HasIncludeMappings returns a boolean if a field has been set.
func (o *CommunicationTemplateOptionsModel) HasIncludeMappings() bool {
	if o != nil && o.IncludeMappings != nil {
		return true
	}

	return false
}

// SetIncludeMappings gets a reference to the given bool and assigns it to the IncludeMappings field.
func (o *CommunicationTemplateOptionsModel) SetIncludeMappings(v bool) {
	o.IncludeMappings = &v
}

func (o CommunicationTemplateOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExcludeTemplateContent != nil {
		toSerialize["exclude_template_content"] = o.ExcludeTemplateContent
	}
	if o.IncludeMappings != nil {
		toSerialize["include_mappings"] = o.IncludeMappings
	}
	return json.Marshal(toSerialize)
}

type NullableCommunicationTemplateOptionsModel struct {
	value *CommunicationTemplateOptionsModel
	isSet bool
}

func (v NullableCommunicationTemplateOptionsModel) Get() *CommunicationTemplateOptionsModel {
	return v.value
}

func (v *NullableCommunicationTemplateOptionsModel) Set(val *CommunicationTemplateOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunicationTemplateOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunicationTemplateOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunicationTemplateOptionsModel(val *CommunicationTemplateOptionsModel) *NullableCommunicationTemplateOptionsModel {
	return &NullableCommunicationTemplateOptionsModel{value: val, isSet: true}
}

func (v NullableCommunicationTemplateOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunicationTemplateOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


