/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiResponse54 struct for ApiResponse54
type ApiResponse54 struct {
	// Message describing the error
	Message *string `json:"message,omitempty"`
	// Error code
	Code *float32 `json:"code,omitempty"`
}

// NewApiResponse54 instantiates a new ApiResponse54 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponse54() *ApiResponse54 {
	this := ApiResponse54{}
	return &this
}

// NewApiResponse54WithDefaults instantiates a new ApiResponse54 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponse54WithDefaults() *ApiResponse54 {
	this := ApiResponse54{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiResponse54) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponse54) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiResponse54) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiResponse54) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ApiResponse54) GetCode() float32 {
	if o == nil || o.Code == nil {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponse54) GetCodeOk() (*float32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ApiResponse54) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *ApiResponse54) SetCode(v float32) {
	o.Code = &v
}

func (o ApiResponse54) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableApiResponse54 struct {
	value *ApiResponse54
	isSet bool
}

func (v NullableApiResponse54) Get() *ApiResponse54 {
	return v.value
}

func (v *NullableApiResponse54) Set(val *ApiResponse54) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponse54) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponse54) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponse54(val *ApiResponse54) *NullableApiResponse54 {
	return &NullableApiResponse54{value: val, isSet: true}
}

func (v NullableApiResponse54) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponse54) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


