/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddressOptionsModel struct for AddressOptionsModel
type AddressOptionsModel struct {
	// 
	IncludePhoneNrs *bool `json:"include_phone_nrs,omitempty"`
	// 
	IncludeEmails *bool `json:"include_emails,omitempty"`
	// 
	IncludeOpeningHours *bool `json:"include_opening_hours,omitempty"`
	// 
	IncludeAddressTags *bool `json:"include_address_tags,omitempty"`
	// 
	IncludePartyInfo *bool `json:"include_party_info,omitempty"`
	// 
	IncludePartyName *bool `json:"include_party_name,omitempty"`
	// 
	IncludeAddressTypeNames *bool `json:"include_address_type_names,omitempty"`
	// 
	IncludeAddressMetaData *bool `json:"include_address_meta_data,omitempty"`
	// 
	IncludeAddressFiles *bool `json:"include_address_files,omitempty"`
	// 
	IncludeAddressNotes *bool `json:"include_address_notes,omitempty"`
	// 
	IncludeLinks *bool `json:"include_links,omitempty"`
}

// NewAddressOptionsModel instantiates a new AddressOptionsModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressOptionsModel() *AddressOptionsModel {
	this := AddressOptionsModel{}
	return &this
}

// NewAddressOptionsModelWithDefaults instantiates a new AddressOptionsModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressOptionsModelWithDefaults() *AddressOptionsModel {
	this := AddressOptionsModel{}
	return &this
}

// GetIncludePhoneNrs returns the IncludePhoneNrs field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludePhoneNrs() bool {
	if o == nil || o.IncludePhoneNrs == nil {
		var ret bool
		return ret
	}
	return *o.IncludePhoneNrs
}

// GetIncludePhoneNrsOk returns a tuple with the IncludePhoneNrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludePhoneNrsOk() (*bool, bool) {
	if o == nil || o.IncludePhoneNrs == nil {
		return nil, false
	}
	return o.IncludePhoneNrs, true
}

// HasIncludePhoneNrs returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludePhoneNrs() bool {
	if o != nil && o.IncludePhoneNrs != nil {
		return true
	}

	return false
}

// SetIncludePhoneNrs gets a reference to the given bool and assigns it to the IncludePhoneNrs field.
func (o *AddressOptionsModel) SetIncludePhoneNrs(v bool) {
	o.IncludePhoneNrs = &v
}

// GetIncludeEmails returns the IncludeEmails field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeEmails() bool {
	if o == nil || o.IncludeEmails == nil {
		var ret bool
		return ret
	}
	return *o.IncludeEmails
}

// GetIncludeEmailsOk returns a tuple with the IncludeEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeEmailsOk() (*bool, bool) {
	if o == nil || o.IncludeEmails == nil {
		return nil, false
	}
	return o.IncludeEmails, true
}

// HasIncludeEmails returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeEmails() bool {
	if o != nil && o.IncludeEmails != nil {
		return true
	}

	return false
}

// SetIncludeEmails gets a reference to the given bool and assigns it to the IncludeEmails field.
func (o *AddressOptionsModel) SetIncludeEmails(v bool) {
	o.IncludeEmails = &v
}

// GetIncludeOpeningHours returns the IncludeOpeningHours field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeOpeningHours() bool {
	if o == nil || o.IncludeOpeningHours == nil {
		var ret bool
		return ret
	}
	return *o.IncludeOpeningHours
}

// GetIncludeOpeningHoursOk returns a tuple with the IncludeOpeningHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeOpeningHoursOk() (*bool, bool) {
	if o == nil || o.IncludeOpeningHours == nil {
		return nil, false
	}
	return o.IncludeOpeningHours, true
}

// HasIncludeOpeningHours returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeOpeningHours() bool {
	if o != nil && o.IncludeOpeningHours != nil {
		return true
	}

	return false
}

// SetIncludeOpeningHours gets a reference to the given bool and assigns it to the IncludeOpeningHours field.
func (o *AddressOptionsModel) SetIncludeOpeningHours(v bool) {
	o.IncludeOpeningHours = &v
}

// GetIncludeAddressTags returns the IncludeAddressTags field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeAddressTags() bool {
	if o == nil || o.IncludeAddressTags == nil {
		var ret bool
		return ret
	}
	return *o.IncludeAddressTags
}

// GetIncludeAddressTagsOk returns a tuple with the IncludeAddressTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeAddressTagsOk() (*bool, bool) {
	if o == nil || o.IncludeAddressTags == nil {
		return nil, false
	}
	return o.IncludeAddressTags, true
}

// HasIncludeAddressTags returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeAddressTags() bool {
	if o != nil && o.IncludeAddressTags != nil {
		return true
	}

	return false
}

// SetIncludeAddressTags gets a reference to the given bool and assigns it to the IncludeAddressTags field.
func (o *AddressOptionsModel) SetIncludeAddressTags(v bool) {
	o.IncludeAddressTags = &v
}

// GetIncludePartyInfo returns the IncludePartyInfo field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludePartyInfo() bool {
	if o == nil || o.IncludePartyInfo == nil {
		var ret bool
		return ret
	}
	return *o.IncludePartyInfo
}

// GetIncludePartyInfoOk returns a tuple with the IncludePartyInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludePartyInfoOk() (*bool, bool) {
	if o == nil || o.IncludePartyInfo == nil {
		return nil, false
	}
	return o.IncludePartyInfo, true
}

// HasIncludePartyInfo returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludePartyInfo() bool {
	if o != nil && o.IncludePartyInfo != nil {
		return true
	}

	return false
}

// SetIncludePartyInfo gets a reference to the given bool and assigns it to the IncludePartyInfo field.
func (o *AddressOptionsModel) SetIncludePartyInfo(v bool) {
	o.IncludePartyInfo = &v
}

// GetIncludePartyName returns the IncludePartyName field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludePartyName() bool {
	if o == nil || o.IncludePartyName == nil {
		var ret bool
		return ret
	}
	return *o.IncludePartyName
}

// GetIncludePartyNameOk returns a tuple with the IncludePartyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludePartyNameOk() (*bool, bool) {
	if o == nil || o.IncludePartyName == nil {
		return nil, false
	}
	return o.IncludePartyName, true
}

// HasIncludePartyName returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludePartyName() bool {
	if o != nil && o.IncludePartyName != nil {
		return true
	}

	return false
}

// SetIncludePartyName gets a reference to the given bool and assigns it to the IncludePartyName field.
func (o *AddressOptionsModel) SetIncludePartyName(v bool) {
	o.IncludePartyName = &v
}

// GetIncludeAddressTypeNames returns the IncludeAddressTypeNames field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeAddressTypeNames() bool {
	if o == nil || o.IncludeAddressTypeNames == nil {
		var ret bool
		return ret
	}
	return *o.IncludeAddressTypeNames
}

// GetIncludeAddressTypeNamesOk returns a tuple with the IncludeAddressTypeNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeAddressTypeNamesOk() (*bool, bool) {
	if o == nil || o.IncludeAddressTypeNames == nil {
		return nil, false
	}
	return o.IncludeAddressTypeNames, true
}

// HasIncludeAddressTypeNames returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeAddressTypeNames() bool {
	if o != nil && o.IncludeAddressTypeNames != nil {
		return true
	}

	return false
}

// SetIncludeAddressTypeNames gets a reference to the given bool and assigns it to the IncludeAddressTypeNames field.
func (o *AddressOptionsModel) SetIncludeAddressTypeNames(v bool) {
	o.IncludeAddressTypeNames = &v
}

// GetIncludeAddressMetaData returns the IncludeAddressMetaData field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeAddressMetaData() bool {
	if o == nil || o.IncludeAddressMetaData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeAddressMetaData
}

// GetIncludeAddressMetaDataOk returns a tuple with the IncludeAddressMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeAddressMetaDataOk() (*bool, bool) {
	if o == nil || o.IncludeAddressMetaData == nil {
		return nil, false
	}
	return o.IncludeAddressMetaData, true
}

// HasIncludeAddressMetaData returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeAddressMetaData() bool {
	if o != nil && o.IncludeAddressMetaData != nil {
		return true
	}

	return false
}

// SetIncludeAddressMetaData gets a reference to the given bool and assigns it to the IncludeAddressMetaData field.
func (o *AddressOptionsModel) SetIncludeAddressMetaData(v bool) {
	o.IncludeAddressMetaData = &v
}

// GetIncludeAddressFiles returns the IncludeAddressFiles field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeAddressFiles() bool {
	if o == nil || o.IncludeAddressFiles == nil {
		var ret bool
		return ret
	}
	return *o.IncludeAddressFiles
}

// GetIncludeAddressFilesOk returns a tuple with the IncludeAddressFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeAddressFilesOk() (*bool, bool) {
	if o == nil || o.IncludeAddressFiles == nil {
		return nil, false
	}
	return o.IncludeAddressFiles, true
}

// HasIncludeAddressFiles returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeAddressFiles() bool {
	if o != nil && o.IncludeAddressFiles != nil {
		return true
	}

	return false
}

// SetIncludeAddressFiles gets a reference to the given bool and assigns it to the IncludeAddressFiles field.
func (o *AddressOptionsModel) SetIncludeAddressFiles(v bool) {
	o.IncludeAddressFiles = &v
}

// GetIncludeAddressNotes returns the IncludeAddressNotes field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeAddressNotes() bool {
	if o == nil || o.IncludeAddressNotes == nil {
		var ret bool
		return ret
	}
	return *o.IncludeAddressNotes
}

// GetIncludeAddressNotesOk returns a tuple with the IncludeAddressNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeAddressNotesOk() (*bool, bool) {
	if o == nil || o.IncludeAddressNotes == nil {
		return nil, false
	}
	return o.IncludeAddressNotes, true
}

// HasIncludeAddressNotes returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeAddressNotes() bool {
	if o != nil && o.IncludeAddressNotes != nil {
		return true
	}

	return false
}

// SetIncludeAddressNotes gets a reference to the given bool and assigns it to the IncludeAddressNotes field.
func (o *AddressOptionsModel) SetIncludeAddressNotes(v bool) {
	o.IncludeAddressNotes = &v
}

// GetIncludeLinks returns the IncludeLinks field value if set, zero value otherwise.
func (o *AddressOptionsModel) GetIncludeLinks() bool {
	if o == nil || o.IncludeLinks == nil {
		var ret bool
		return ret
	}
	return *o.IncludeLinks
}

// GetIncludeLinksOk returns a tuple with the IncludeLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressOptionsModel) GetIncludeLinksOk() (*bool, bool) {
	if o == nil || o.IncludeLinks == nil {
		return nil, false
	}
	return o.IncludeLinks, true
}

// HasIncludeLinks returns a boolean if a field has been set.
func (o *AddressOptionsModel) HasIncludeLinks() bool {
	if o != nil && o.IncludeLinks != nil {
		return true
	}

	return false
}

// SetIncludeLinks gets a reference to the given bool and assigns it to the IncludeLinks field.
func (o *AddressOptionsModel) SetIncludeLinks(v bool) {
	o.IncludeLinks = &v
}

func (o AddressOptionsModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludePhoneNrs != nil {
		toSerialize["include_phone_nrs"] = o.IncludePhoneNrs
	}
	if o.IncludeEmails != nil {
		toSerialize["include_emails"] = o.IncludeEmails
	}
	if o.IncludeOpeningHours != nil {
		toSerialize["include_opening_hours"] = o.IncludeOpeningHours
	}
	if o.IncludeAddressTags != nil {
		toSerialize["include_address_tags"] = o.IncludeAddressTags
	}
	if o.IncludePartyInfo != nil {
		toSerialize["include_party_info"] = o.IncludePartyInfo
	}
	if o.IncludePartyName != nil {
		toSerialize["include_party_name"] = o.IncludePartyName
	}
	if o.IncludeAddressTypeNames != nil {
		toSerialize["include_address_type_names"] = o.IncludeAddressTypeNames
	}
	if o.IncludeAddressMetaData != nil {
		toSerialize["include_address_meta_data"] = o.IncludeAddressMetaData
	}
	if o.IncludeAddressFiles != nil {
		toSerialize["include_address_files"] = o.IncludeAddressFiles
	}
	if o.IncludeAddressNotes != nil {
		toSerialize["include_address_notes"] = o.IncludeAddressNotes
	}
	if o.IncludeLinks != nil {
		toSerialize["include_links"] = o.IncludeLinks
	}
	return json.Marshal(toSerialize)
}

type NullableAddressOptionsModel struct {
	value *AddressOptionsModel
	isSet bool
}

func (v NullableAddressOptionsModel) Get() *AddressOptionsModel {
	return v.value
}

func (v *NullableAddressOptionsModel) Set(val *AddressOptionsModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressOptionsModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressOptionsModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressOptionsModel(val *AddressOptionsModel) *NullableAddressOptionsModel {
	return &NullableAddressOptionsModel{value: val, isSet: true}
}

func (v NullableAddressOptionsModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressOptionsModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


