/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CommunicationMessageFiltersModel struct for CommunicationMessageFiltersModel
type CommunicationMessageFiltersModel struct {
	// Bumbal Activity ID
	ActivityId *int32 `json:"activity_id,omitempty"`
}

// NewCommunicationMessageFiltersModel instantiates a new CommunicationMessageFiltersModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunicationMessageFiltersModel() *CommunicationMessageFiltersModel {
	this := CommunicationMessageFiltersModel{}
	return &this
}

// NewCommunicationMessageFiltersModelWithDefaults instantiates a new CommunicationMessageFiltersModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunicationMessageFiltersModelWithDefaults() *CommunicationMessageFiltersModel {
	this := CommunicationMessageFiltersModel{}
	return &this
}

// GetActivityId returns the ActivityId field value if set, zero value otherwise.
func (o *CommunicationMessageFiltersModel) GetActivityId() int32 {
	if o == nil || o.ActivityId == nil {
		var ret int32
		return ret
	}
	return *o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunicationMessageFiltersModel) GetActivityIdOk() (*int32, bool) {
	if o == nil || o.ActivityId == nil {
		return nil, false
	}
	return o.ActivityId, true
}

// HasActivityId returns a boolean if a field has been set.
func (o *CommunicationMessageFiltersModel) HasActivityId() bool {
	if o != nil && o.ActivityId != nil {
		return true
	}

	return false
}

// SetActivityId gets a reference to the given int32 and assigns it to the ActivityId field.
func (o *CommunicationMessageFiltersModel) SetActivityId(v int32) {
	o.ActivityId = &v
}

func (o CommunicationMessageFiltersModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActivityId != nil {
		toSerialize["activity_id"] = o.ActivityId
	}
	return json.Marshal(toSerialize)
}

type NullableCommunicationMessageFiltersModel struct {
	value *CommunicationMessageFiltersModel
	isSet bool
}

func (v NullableCommunicationMessageFiltersModel) Get() *CommunicationMessageFiltersModel {
	return v.value
}

func (v *NullableCommunicationMessageFiltersModel) Set(val *CommunicationMessageFiltersModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunicationMessageFiltersModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunicationMessageFiltersModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunicationMessageFiltersModel(val *CommunicationMessageFiltersModel) *NullableCommunicationMessageFiltersModel {
	return &NullableCommunicationMessageFiltersModel{value: val, isSet: true}
}

func (v NullableCommunicationMessageFiltersModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunicationMessageFiltersModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


