/*
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * API version: 2.0
 * Contact: info@bumbal.eu
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceWindowModel struct for ServiceWindowModel
type ServiceWindowModel struct {
	// Unique ID
	Id *int64 `json:"id,omitempty"`
	// Service windows scheme ID
	ServiceWindowsSchemeId *int64 `json:"service_windows_scheme_id,omitempty"`
	// Week day
	WeekDay *int64 `json:"week_day,omitempty"`
	// time from
	TimeFrom *string `json:"time_from,omitempty"`
	// time to
	TimeTo *string `json:"time_to,omitempty"`
}

// NewServiceWindowModel instantiates a new ServiceWindowModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceWindowModel() *ServiceWindowModel {
	this := ServiceWindowModel{}
	return &this
}

// NewServiceWindowModelWithDefaults instantiates a new ServiceWindowModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWindowModelWithDefaults() *ServiceWindowModel {
	this := ServiceWindowModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceWindowModel) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowModel) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceWindowModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ServiceWindowModel) SetId(v int64) {
	o.Id = &v
}

// GetServiceWindowsSchemeId returns the ServiceWindowsSchemeId field value if set, zero value otherwise.
func (o *ServiceWindowModel) GetServiceWindowsSchemeId() int64 {
	if o == nil || o.ServiceWindowsSchemeId == nil {
		var ret int64
		return ret
	}
	return *o.ServiceWindowsSchemeId
}

// GetServiceWindowsSchemeIdOk returns a tuple with the ServiceWindowsSchemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowModel) GetServiceWindowsSchemeIdOk() (*int64, bool) {
	if o == nil || o.ServiceWindowsSchemeId == nil {
		return nil, false
	}
	return o.ServiceWindowsSchemeId, true
}

// HasServiceWindowsSchemeId returns a boolean if a field has been set.
func (o *ServiceWindowModel) HasServiceWindowsSchemeId() bool {
	if o != nil && o.ServiceWindowsSchemeId != nil {
		return true
	}

	return false
}

// SetServiceWindowsSchemeId gets a reference to the given int64 and assigns it to the ServiceWindowsSchemeId field.
func (o *ServiceWindowModel) SetServiceWindowsSchemeId(v int64) {
	o.ServiceWindowsSchemeId = &v
}

// GetWeekDay returns the WeekDay field value if set, zero value otherwise.
func (o *ServiceWindowModel) GetWeekDay() int64 {
	if o == nil || o.WeekDay == nil {
		var ret int64
		return ret
	}
	return *o.WeekDay
}

// GetWeekDayOk returns a tuple with the WeekDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowModel) GetWeekDayOk() (*int64, bool) {
	if o == nil || o.WeekDay == nil {
		return nil, false
	}
	return o.WeekDay, true
}

// HasWeekDay returns a boolean if a field has been set.
func (o *ServiceWindowModel) HasWeekDay() bool {
	if o != nil && o.WeekDay != nil {
		return true
	}

	return false
}

// SetWeekDay gets a reference to the given int64 and assigns it to the WeekDay field.
func (o *ServiceWindowModel) SetWeekDay(v int64) {
	o.WeekDay = &v
}

// GetTimeFrom returns the TimeFrom field value if set, zero value otherwise.
func (o *ServiceWindowModel) GetTimeFrom() string {
	if o == nil || o.TimeFrom == nil {
		var ret string
		return ret
	}
	return *o.TimeFrom
}

// GetTimeFromOk returns a tuple with the TimeFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowModel) GetTimeFromOk() (*string, bool) {
	if o == nil || o.TimeFrom == nil {
		return nil, false
	}
	return o.TimeFrom, true
}

// HasTimeFrom returns a boolean if a field has been set.
func (o *ServiceWindowModel) HasTimeFrom() bool {
	if o != nil && o.TimeFrom != nil {
		return true
	}

	return false
}

// SetTimeFrom gets a reference to the given string and assigns it to the TimeFrom field.
func (o *ServiceWindowModel) SetTimeFrom(v string) {
	o.TimeFrom = &v
}

// GetTimeTo returns the TimeTo field value if set, zero value otherwise.
func (o *ServiceWindowModel) GetTimeTo() string {
	if o == nil || o.TimeTo == nil {
		var ret string
		return ret
	}
	return *o.TimeTo
}

// GetTimeToOk returns a tuple with the TimeTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceWindowModel) GetTimeToOk() (*string, bool) {
	if o == nil || o.TimeTo == nil {
		return nil, false
	}
	return o.TimeTo, true
}

// HasTimeTo returns a boolean if a field has been set.
func (o *ServiceWindowModel) HasTimeTo() bool {
	if o != nil && o.TimeTo != nil {
		return true
	}

	return false
}

// SetTimeTo gets a reference to the given string and assigns it to the TimeTo field.
func (o *ServiceWindowModel) SetTimeTo(v string) {
	o.TimeTo = &v
}

func (o ServiceWindowModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.ServiceWindowsSchemeId != nil {
		toSerialize["service_windows_scheme_id"] = o.ServiceWindowsSchemeId
	}
	if o.WeekDay != nil {
		toSerialize["week_day"] = o.WeekDay
	}
	if o.TimeFrom != nil {
		toSerialize["time_from"] = o.TimeFrom
	}
	if o.TimeTo != nil {
		toSerialize["time_to"] = o.TimeTo
	}
	return json.Marshal(toSerialize)
}

type NullableServiceWindowModel struct {
	value *ServiceWindowModel
	isSet bool
}

func (v NullableServiceWindowModel) Get() *ServiceWindowModel {
	return v.value
}

func (v *NullableServiceWindowModel) Set(val *ServiceWindowModel) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceWindowModel) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceWindowModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceWindowModel(val *ServiceWindowModel) *NullableServiceWindowModel {
	return &NullableServiceWindowModel{value: val, isSet: true}
}

func (v NullableServiceWindowModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceWindowModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


